services:
  - type: web
    name: restaurant-pos
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crcs-bergeggi-db
          property: connectionString
  
  - type: pserv
    name: crcs-bergeggi-db
    env: postgresql
    plan: free
    databaseName: restaurant_pos
    user: restaurant_user